config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'books#index'

  resources :books do
    get 'reading_path', on: :member
    resources :chapters do
      put 'toggle_read', to: 'chapters#toggle_read', on: :member
    end
    resources :dependencies
  end

  resources :suggestions
end

app/models/dependency.rb
class Dependency < ApplicationRecord
  belongs_to :parent, class_name: 'Book'
  belongs_to :child, class_name: 'Book'

  validate :self_reference


  private

  def self_reference
    errors.add(:self_referencing, "Self referencing is prohibited #{self.parent_id} -> #{self.child_id}") if self.parent_id == self.child_id
  end
end

app/controllers/dependencies_controller.rb
class DependenciesController < ApplicationController
  before_action :set_book
  
  def index

  end

  def show
    
  end

  def new
    
  end

  def create
    @book.book_children.build get_array_of_hashes_for_nested_resources(dependency_params)
    if @book.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def dependency_params
    params.permit(child_ids: [])
  end
end

app/helpers/dependencies_helper.rb
module DependenciesHelper
end

app/views/dependencies/_form.html.erb
<%= render partial: "layouts/form_error", locals:{errors: @book.errors}%> 


<%=  form_tag book_dependencies_url(@book), method: method do %>

<div class='form-group'>
  <%= label_tag :children %>
  <%= select_tag :child_ids, options_for_select(@book.others.collect { |r| [ r.name, r.id ] }), multiple: true, class: 'form-control', blank: false %>
</div>
<%= submit_tag submitText,  class: 'btn btn-primary' %>

<% end %>

<script>
  $('select').select2({
  theme: 'bootstrap'
  });
</script>

app/views/dependencies/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-12'>
      <div class='card'>
        <div class='card-header bg-info'>
          <h3>Add postrequisits to <%= @book.name %></h3>
        </div>
        <div class='card-body'>
          <%= render partial: 'form', locals: {submitText: 'Add new dependants', method: :post} %>
        </div>
      </div>
    </div>
  </div>
</div>