config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'books#index'

  resources :books do
    get 'reading_path', on: :member
    resources :chapters do
      put 'toggle_read', to: 'chapters#toggle_read', on: :member
    end
    resources :dependencies
  end

  resources :suggestions
end

app/models/book.rb
class Book < ApplicationRecord
  include BooksHelper

  has_many :chapters
  has_many :book_parents, class_name: 'Dependency', foreign_key: :child_id
  has_many :book_children, class_name: 'Dependency', foreign_key: :parent_id

  has_many :parents, through: :book_parents
  has_many :children, through: :book_children
  
  before_save :contains_cycle?

  validates :name, presence: true, length: {minumum: 3, maximum: 100}
  validates :description, length: {maximum: 1.kilobyte}

  accepts_nested_attributes_for :children, allow_destroy: true
  
  scope :others, -> (id) { where('id != ?', id) }

  def others
    Book.all.where('id != ?', id)
  end

  private
  def contains_cycle?
    old_dependencies = Dependency.all
    new_dependencies = book_children
    dependencies = old_dependencies + new_dependencies - (old_dependencies & new_dependencies)
    edges = dependencies.collect { |r| [r.parent_id, r.child_id] }
    extract_forest_for_vertex(edges, self.id)
    graph = Graph.new do |e|
      e = edges
    end
    cycles = graph.get_cycles
    format_error_messages_for_circular_dependency cycles unless cycles.empty?
    throw(:abort) unless cycles.length.zero?
  end

  def format_error_messages_for_circular_dependency(cycles) 
    cycles.each_with_index do |cycle, index|
      error_message = cycle.map { |book_id| Book.find(book_id) }.map(&:name).join(' -> ')
      self.errors.add("Cycle ##{index}", error_message)
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper

  before_action :set_book, only: %i[show edit edit update destroy reading_path]

  def index
    paginate(Book.all, params[:page]) do |books|
      @books = books
      respond_to do |format|
        format.html
        format.json { json(@books) }
      end
    end
  end

  def show; end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      redirect_to books_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    @book.update_attributes book_params
    if @book.errors.blank?
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book.delete
    redirect_to root_path
  end

  def reading_path
    graph = load_inverted_dependency_graph_for(@book)
    graph.set_traversal(DfsTraversal.new)
    graph.set_prioritizer GraphFactory.make_prioritizer(:dag_dfs)
    graph.prioritizer.starting_point = @book.id
    needed_vertices = Set.new graph.traverse(@book.id)
    graph.graph = clean_graph(graph.graph, needed_vertices)
    @priorities = get_priorities_from(graph)
    @priorities = get_book_models_from @priorities
  end

  private

  def set_book
    @book = Book.find params[:id]
  end

  def book_params
    params.require(:book).permit(:name, :description)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def book_completed_percentage(book)
    return 0 if book.chapters.length.zero?
    book.chapters.completed.pages.to_f / book.chapters.pages.to_f
  end

  def book_completed_percentage_for_html(book)
    (book_completed_percentage(book) * 100).to_i
  end

  def suitable_color(book)
    color_levels = %w[danger warning info primary success]
    color_levels[(book_completed_percentage(book) * (color_levels.length - 1)).to_i]
  end

  def load_inverted_dependency_graph_for(book)
    edges = Dependency.find_each.collect do |r|
      [r.child_id, r.parent_id]
    end
    extract_forest_for_vertex(edges, book.id)
  end

  def extract_forest_for_vertex(edges, vertex)
    uf = UnionFind.new
    edges.each do |r|
      uf.union(r[0], r[1])
    end
    edges = clean_edges(edges, uf, vertex)
    graph = Graph.new do |e|
      e = edges
    end
  end

  def clean_edges(edges, sets, vertex)
    compact_edges = []
    edges.each do |edge|
      child = edge[0]
      if sets.is_same_set(vertex, child)
        compact_edges << edge
      end
    end
    compact_edges
  end

  def clean_graph(graph, needed_vertices)
    graph.delete_if { |key, _| needed_vertices.exclude? key }
    graph.transform_values do |neighbors|
      neighbors.delete_if { |neighbor| needed_vertices.exclude? neighbor }
    end
    graph
  end

  def delete_unneeded_priorities(priorities, book)
    specified_priority = get_specified_priority(priorities, book.id)
    priorities.delete_if { |key, _| key > specified_priority }  
  end
  
  def get_specified_priority(priorities, id)
    priority = nil
    priorities.keys.reverse.each do |key|
      break unless priority.nil?
      priorities[key].each do |book_id|
        break unless priority.nil?
        priority = key if book_id == id
      end
    end
    priority
  end

  def rearrange_priorities(priorities)
    max_priority = priorities.keys.max
    priorities.transform_keys { |key| max_priority - key + 1 }.sort_by { |key, _| key }.to_h
  end

end

app/views/books/_book.html.erb
<div class='row'>
  <div class='col-3'>
    <%= link_to "#{book.name} (#{book.chapters.pages} pages)", book %>
  </div>
  <div class='col-9'>
    <%= render book.chapters %>
  </div>                  
</div>
<br>
<div class='row'>
  <div class='offset-3 col-8'>
    <%= render partial: 'progress', locals: { book: book } %>
  </div>
</div>
<br>
<div class='row'>
  <div class='col-4 offset-5'>
    <%= link_to new_book_chapter_url(book), class: 'btn btn-primary btn-block' do %>
      <%= fa_icon 'plus', text: 'Add new chapter' %>
    <% end %>
  </div>
</div>
<hr>

  

app/views/books/_form.html.erb
<%= render partial: "layouts/form_error", locals:{errors: @book.errors}%> 
<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%=f.text_field :name , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%=f.text_field :description , class: "form-control"%>
  </div>
  <%= f.submit class: "btn btn-outline-dark btn-block"%>
<% end %>
    

app/views/books/_progress.html.erb
<div class="progress">
  <div class="progress-bar bg-<%= suitable_color(book) %>" role="progressbar" style="width: <%= book_completed_percentage_for_html(book) %>%;" aria-valuenow="<%= book_completed_percentage_for_html(book) %>" aria-valuemin="0" aria-valuemax="100">
    
    <%= book.chapters.completed.length %> Chapters completed
    (<%= book_completed_percentage_for_html(book) %>%)
  
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= render "form" %>
    </div> 
  </div>
</div>

app/views/books/index.html.erb
<div class='container'>
  <div class='row'>
      <div class='col-3'>
        <h3>Title</h3>      
      </div>
      <div class='col-9'>
        <h3>chapters</h3>      
      </div>
  </div>
  <%= render @books %>
  <div class='row'>
    <div class='col-12'>
      <%= paginate @books %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= render "form" %>
    </div> 
  </div>
</div>
  

app/views/books/reading_path.html.erb
<div class='container'>
<div class='row'>
  <div class='col-12'>
    <h3>Suggested Reading path for <%= @book.name %></h3>
  </div>
</div>
<%= render partial: 'shared/book_priority_table', locals: {priorities: @priorities} %>

app/views/books/show.html.erb
<!-- <%= @book.name %><br> -->
<!-- <%= @book.description%><br>
<%= link_to  "edit", edit_book_url(@book) %><br>
<%= link_to  "delete", book_url(@book), method: :delete, data: {confirm: "Are you sure?"} %><br>
<%= render @book.chapters%> -->

<div class="container">
  <div class="row">
    <div class="col-11">
      <table class='table table-hover'>
        <tr>
          <th>Name</th>
          <td><%= @book.name %></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%= @book.description %></td>
        </tr>
        <tr>
          <th>Chapters</th>
          <td><%= render @book.chapters %></td>
        </tr>
        <tr>
          <th>Progress</th>
          <td>
            <%= render partial: 'progress', locals: { book: @book} %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-1">
      <%= link_to edit_book_url(@book) do %>
        <%= fa_icon 'edit', class: 'text-primary', style: 'font-size: 20px' %>
      <% end %>
      <%= link_to book_url(@book), method: :delete, data: {confirm: "Are you sure?"}, style: 'font-size: 20px'  do %>
        <%= fa_icon 'trash', class: 'text-danger' %>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class='col-12'>
      <div class='btn-group d-flex justify-content-center' role='group'>
          <%= link_to 'Suggested Reading Path', reading_path_book_url(@book), class: 'btn btn-info' %>
          <%= link_to 'Add new postrequisits', new_book_dependency_url(@book), class: 'btn btn-dark' %>
          <%= link_to "Add new chapter", new_book_chapter_url(@book), class: 'btn btn-primary' %>
      </div>
    </div>
    <!-- <div class='col-3'>
      <%= link_to 'Suggested Reading Path', reading_path_book_url(@book), class: 'btn btn-blocl btn-info' %>
    </div>
    <div class='offset-5 col-3'>
      <%= link_to "Add new chapter", new_book_chapter_url(@book), class: 'btn btn-block btn-primary' %>
    </div> -->
  </div>
</div>