config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'books#index'

  resources :books do
    get 'reading_path', on: :member
    resources :chapters do
      put 'toggle_read', to: 'chapters#toggle_read', on: :member
    end
    resources :dependencies
  end

  resources :suggestions
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :book
  validates :name, presence: true, length: {minumum: 3, maximum: 100}
  validates :number_of_pages, presence: true, numericality: { only_integer: true, greater_than: 0}

  scope :completed, -> { where(is_read: true) }

  scope :pages, -> { sum(:number_of_pages) }


  def toggle_read
    update_attribute(:is_read, !is_read)
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: %i[show edit update destroy toggle_read]
  before_action :set_book

  def index
    @chapters = @book.chapters
  end

  def new
    @chapter = Chapter.new
    session[:redirect_to] = request.referrer || root_url
  end

  def create
    @chapter = @book.chapters.build chapter_params
    if @chapter.save
      redirect_to session[:redirect_to] || @book
    else
      render 'new'
    end
  end

  def edit;end

  def update
    @chapter.update_attributes chapter_params
    if @chapter.errors.blank?
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @chapter.delete
    redirect_to @book
  end

  def toggle_read
    @chapter.toggle_read
    redirect_back fallback_location: root_url
  end

  private

  def set_book
    @book = Book.find params[:book_id]
  end

  def set_chapter
    @chapter = Book.find(params[:book_id]).chapters.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:name, :number_of_chapter, :number_of_pages)
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_chapter.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-8'>
      <%= link_to "#{chapter_counter + 1}- #{chapter.name} (#{chapter.number_of_pages} pages)", book_chapter_url(chapter.book, chapter) %>
    </div>
    <div class='col-2 offset-2'>
      <%= link_to toggle_read_book_chapter_url(chapter.book, chapter), method: :put do %>
        <% if chapter.is_read %>
          <%= fa_icon 'times', class: 'text-danger' %>
        <% else %>
          <%= fa_icon 'check', class: 'text-success' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/chapters/_form.html.erb
<%= render partial: "layouts/form_error", locals: { errors: @chapter.errors } %> 
<%= form_for [@book, @chapter] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%=f.text_field :name , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_pages %>
    <%= f.number_field :number_of_pages , class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-outline-dark btn-block"%>
<% end %>
    

app/views/chapters/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= render "form" %>
    </div> 
  </div>
</div>

app/views/chapters/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= render "form" %>
    </div> 
  </div>
</div>
  

app/views/chapters/show.html.erb
<%= @chapter.name %><br>
<%=  "Number of pages: #{@chapter.number_of_pages}"%><br>
<%= link_to  "edit", edit_book_chapter_url(@book, @chapter) %><br>
<%= link_to  "delete", book_chapter_url(@book, @chapter), method: :delete, data: {confirm: "Are you sure?"} %><br>