config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'books#index'

  resources :books do
    get 'reading_path', on: :member
    resources :chapters do
      put 'toggle_read', to: 'chapters#toggle_read', on: :member
    end
    resources :dependencies
  end

  resources :suggestions
end

app/views/layouts/_form_error.html.erb
<% if errors.any? %>
  <div class="alert alert-danger alert-dismissible">
    <% errors.full_messages.each do |error| %>
      <p><%=error%></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BookTrack</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
      <div class="sidebar-header">
        <h3>Book Tracking</h3>
      </div>

      <ul class="list-unstyled components">
        <p>Sites</p>
        <li>
          <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">Books</a>
          <ul class="collapse list-unstyled" id="homeSubmenu">
            <li><%= link_to 'List', books_url %></li>
            <li><%= link_to 'New Book', new_book_url %></li>
          </ul>
        </li>
        <li>
          <%= link_to 'Suggestion', suggestions_url %>
        </li>
      </ul>
    </nav>

    <!-- Page Content Holder -->
    <div id="content">

      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" id="sidebarCollapse" class="navbar-btn">
              <span></span>
              <span></span>
              <span></span>
            </button>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="#">Page</a>
              </li>
              <li>
                <a href="#">Page</a>
              </li>
              <li>
                <a href="#">Page</a>
              </li>
              <li>
                <a href="#">Page</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <%= yield %>
      
    </div>
  </div>
</body>

</html>